// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InsertInListController from "./insert_in_list_controller"
application.register("insert-in-list", InsertInListController)

import MapController from "./map_controller"
application.register("map", MapController)

import NavbarDropdownController from "./navbar_dropdown_controller"
application.register("navbar-dropdown", NavbarDropdownController)

import TogglemapController from "./togglemap_controller"
application.register("togglemap", TogglemapController)

import TotalPriceController from "./total_price_controller"
application.register("total-price", TotalPriceController)

import TypedJsController from "./typed_js_controller"
application.register("typed-js", TypedJsController)
